### ISSUE TITLE
Bug:running prisma generate gets stuck when using the generator

### ISSUE THREAD

**Issue by ishakdeveloper** [YassinEldeeb/prisma-tgql-types-gen#62] opened 2022-07-17 10:08 UTC
## Bug description
Whenever i run "yarn prisma generate" with the generator in the prisma schema, it gets stuck. (This ONLY happens when i have the generator in the prisma schema)

## To Reproduce
1. Add the generator with yarn or npm
2. put the generator in the prisma schema
3. run yarn prisma generate
4. See the problem

## Expected behavior
Making the generator work with the properties in the prisma schema. Prisma generate should not get stuck when using this library.

## Screenshots
<img width="661" alt="Screenshot 2022-07-17 at 12 01 07" src="https://user-images.githubusercontent.com/55481431/179393429-cf8d8ef9-dcda-4e60-84b3-d400b131c233.png">
![Screenshot 2022-07-17 at 12 05 24](https://user-images.githubusercontent.com/55481431/179393435-bdb4a2cc-cf94-434c-b8fb-d3cc9bda1035.png)

## Prisma information
I have tried using the same prisma schema file as in the example, still the same problem.

## Environment & setup
- OS: Mac OS (M1, Monterey)
- Database: PosstgreSQL
- Node.js version: 18.4.0

## Prisma  Version
3.15.2

**Comment by YassinEldeeb** [comment] 2022-07-17 13:46
This's a very frustrating issue related to https://github.com/YassinEldeeb/prisma-tgql-types-gen/issues/58 and is caused due to the provider script. Sometimes it requires npx, sometimes not and sometimes it requires you to run it with node directly using the relative path to the .bin file like this `node ../node_modules/.bin/prisma-typegraphql-types-gen`. And it's definitely something related to Prisma generators SDKs not being reliable. So please try different ways to include the provider script till it works for you. Cause personally I don't think there's a one right way as it's variable for me too.

**Comment by ishakdeveloper** [comment] 2022-07-17 16:14
I tried running it through node_modules and i now get the following error:

Error: Generator at node ../../node_modules/.bin/prisma-typegraphql-types-generator could not start:
const chalk_1 = __importDefault(require("chalk"));
Error [ERR_REQUIRE_ESM]: require() of ES Module - node_modules/prisma-typegraphql-types-generator/dist/utils/logger.js not supported.

I have also tried using yarn instead of node or npx, also not working. Could turborepo or a monorepo in general be the cause? i will try using the library in a different project

**Comment by YassinEldeeb** [comment] 2022-07-17 17:56
> I have also tried using yarn instead of node or npx, also not working. Could turborepo or a monorepo in general be the cause? i will try using the library in a different project

No it has nothing to do with the issue, but just because the ``

**Comment by YassinEldeeb** [comment] 2022-07-17 17:58
Using node node_modules did work for you. It's just erroring out because chalk is a package that's using the experimental ES module which in my package I don't have it enable as I'm compiling a commonjs build using TSC.

**Comment by YassinEldeeb** [comment] 2022-07-17 17:59
So no worries, you're on the right track with node node_modules script. It's just something that needs to be fixed on my side.

**Comment by ishakdeveloper** [comment] 2022-07-18 15:30
Alright, i cloned the repo and did some debugging. Changed chalk to version 4.1.2 which made the generator work, but it generated empty folders, this is related to issue #44 

In my own project i changed the generator to use version 1.5.11 which is the last version that does not use chalk, which also made the generator work but then it hangs at "Prisma Typegraphql Types Generator:Registered"   

![Screenshot 2022-07-18 at 17 30 24](https://user-images.githubusercontent.com/55481431/179547173-67804f0f-6f61-4ed3-92a5-f104d5c8e41a.png)

**Comment by YassinEldeeb** [comment] 2022-07-18 17:05
Thanks for jumping into debugging it. Really appreciate it. The problem is that I've no clue what could possibly be the issue on MacOS, I've only tested it on windows and Linux which seems to work perfectly fine. So sorry but I've no idea what can be the issue cause.

**Comment by NexZhu** [comment] 2022-07-19 09:15
@YassinEldeeb I'm experiencing the same issue on Windows with WSL (CentOS)

**Comment by YassinEldeeb** [comment] 2022-07-19 11:34
Hey @NexZhu @ishakdeveloper 👋

I've migrated the project to use everything prisma 4 + used the older version of Chalk as @ishakdeveloper has mentioned which worked on both Windows and Linux as I've tested it.

Can you check it now? (Make sure you're on prisma 4 and prisma-typegraphql-types-gen version 1.5.14)

**Comment by ishakdeveloper** [comment] 2022-07-19 12:05
Yes most of it is working now! Only the types are not correct when using the generated models, prisma throws the not assignable error on queries and mutations (This could be something wrong on my part)

**Comment by YassinEldeeb** [comment] 2022-07-19 12:29
Cool! Let me know more about your issue if it turned out to be not yours.

btw, are you on MacOS? If that's the case then I'll close #44 as well.

**Comment by ishakdeveloper** [comment] 2022-07-19 13:42
Yes im also on Mac, works perfectly now :)

**Comment by YassinEldeeb** [comment] 2022-07-19 13:53
Awesome! I guess I'll close both of the issues then.

**Closed by YassinEldeeb** 2022-07-19 13:53 UTC
Labels: bug, help wanted

**Comment by NexZhu** [comment] 2022-07-20 09:19
@YassinEldeeb On Windows with WSL (CentOS), `1.15.14` generated empty `enums` and `models` directories, while `typegraphql-prisma` works as expected, producing enums and models. Sample `schema.prisma`:

```
// refract https://github.com/cwqt/refract - generated in 1.645 ms -----------------
// datasource ----------------------------------------------------------------------

datasource db {
	provider           = "postgresql"
	url                = env("POSTGRES_URL")
	shadowDatabaseUrl  = env("POSTGRES_SHADOW_URL")
}

// generators ----------------------------------------------------------------------

generator client {
	provider         = "prisma-client-js"
	previewFeatures  = []
}

generator PrismaTypeGraphQLTypesGenerator {
    provider     = "npx prisma-typegraphql-types-generator"
    modelsOutput = "./src/graphql/prisma/generated/models"
    enumsOutput  = "./src/graphql/prisma/generated/enums"
    // exportedNameSuffix = "GQL" // Optional if you want to add a suffix to the end of your exported class names and enums
    // exportedNamePrefix = "TYPE" // Optional if you want to prefix your exported class names and enums
}

// generator typegraphql {
// 	provider  = "typegraphql-prisma"
// 	output    = "../src/graphql/prisma/generated"
// }

// enums ---------------------------------------------------------------------------

enum Role {
	// user
	user
	// admin
	admin
}

// models --------------------------------------------------------------------------

model User {
	id         Int       @id @default(autoincrement())
	createdAt  DateTime  @default(now())
	updatedAt  DateTime  @updatedAt
	email      String    @unique
	name       String?
	role       Role      @default(user)
	posts      Post[]
	profile    Profile?
}

model Profile {
	id      Int      @id @default(autoincrement())
	bio     String?
	user    User     @relation(fields: [userId], references: [id])
	userId  Int      @unique
}

model Post {
	id          Int         @id @default(autoincrement())
	createdAt   DateTime    @default(now())
	updatedAt   DateTime    @updatedAt
	title       String
	content     String
	published   Boolean     @default(false)
	author      User?       @relation(fields: [authorId], references: [id])
	authorId    Int?
	categories  Category[]
}

model Category {
	id         Int       @id @default(autoincrement())
	createdAt  DateTime  @default(now())
	updatedAt  DateTime  @updatedAt
	name       String
	posts      Post[]
}
```
